---
on:
  push:
    branches-ignore: []
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+**
    paths:
      - action.yml
      - index.js
      - package.json
      - .github/workflows/ci.yml
name: ci
jobs:
  build:
    name: build dist/index.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm ci

      - name: Compile action
        run: npm run build

      - name: Remove node_modules directory
        run: rm -r ./node_modules

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: ./

  test_create:
    name: test secret creation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: main
          path: ./

      - name: Create a secret
        id: self
        uses: ./
        with:
          name: TEST_${{ github.sha }}
          value: test
          pa_token: ${{ secrets.PA_TOKEN_PIPELINE }}

      - name: Assert action output
        if: steps.self.outputs.status != '201'
        run: echo "::error::Expected HTTP status code 201 got
          ${{steps.self.outputs.status}}"; exit 1

      - name: Confirm secret creation
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/actions/secrets/:secret_name
          repository: ${{ github.repository }}
          secret_name: TEST_${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN_PIPELINE }}

      - name: Delete secret
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/:repository/actions/secrets/:secret_name
          repository: ${{ github.repository }}
          secret_name: TEST_${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN_PIPELINE }}

  test_update:
    name: test secret update
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: main
          path: ./

      - name: Update a secret
        id: self
        uses: ./
        with:
          name: TEST_UPDATE
          value: ${{ github.sha }}
          pa_token: ${{ secrets.PA_TOKEN_PIPELINE }}

      - name: Assert action output
        if: steps.self.outputs.status != '204'
        run: echo "::error::Expected HTTP status code 204 got
          ${{steps.self.outputs.status}}"; exit 1

  release:
    name: release new version
    if: contains(fromJson('["refs/heads/master","refs/heads/next"]'),
      github.ref)
    runs-on: ubuntu-latest
    needs:
      - test_create
      - test_update
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: main
          path: ./

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm ci

      - name: Create new release
        run: npm run release
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ github.token }}

  cleanup:
    name: cleanup
    if: always()
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Delete run artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: main
